# application.properties 공식 reference
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html

# 서버 포트 번호
server:
  port: 8094


spring:
  # 콘솔 ANSI 색상
  output:
    ansi:
      enabled: always

# Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

# datasource 설정.  MySql등 spring-jdbc 사용시 아래 정보 없으면 서버가동 에러.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb2304?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: myuser2304
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

    # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
    # create: 서버 가동할때마다 기존 테이블을 삭제하고 새로 생성
    # update: DB테이블와 엔티티 매핑정보를 비교해서 변경사항이 있는 경우만 수정 (ALTER). 테이블 없으면 CREATE
    # create-drop: 기본적으로 create와 동일한 동작을 하나, 종료시점에서 drop
    hibernate:
      ddl-auto: create


  mail:
    host: smtp.gmail.com
    port: 587
    username: fnrrlfnrrl3@gmail.com
    password: tdgvlqdiznlubbco
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 각종 설정값들을 임의로 설정한뒤 @Value 로 설정값을 주입받아 사용 가능

app:
  # 페이징 관련 세팅값
  pagination:
    # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지를 표시
    write_pages: 10
    # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?
    page_rows: 10

  # 파일업로드경로
  upload:
    path: upload
